### ISSUE TITLE
Feature Request: Remove Default Categories

### ISSUE THREAD

**Issue by roleoutgames** [jessev14/custom-character-sheet-sections#10]
I have several players that would like to use this module to organize their features my class, racial etc. But this leaves the default categories of Active Abilities and Passive Abilities Empty and taking up space. Can you implement an option to deactivate or hide empty sections?

**Comment by jessev14** [comment]
This might be doable but is a little outside the scope of this module. Have you considered using [Inventory+](https://foundryvtt.com/packages/inventory-plus)? It should let you delete the default categories and I believe create custom categories as well.

**Comment by roleoutgames** [comment]
I have used it before but as far as I know, it is restricted to the inventory and wouldn't do what I want in the feature tab.

**Comment by jessev14** [comment]
Added a module setting to hide empty headers. Available in 1.5.0.
