### ISSUE TITLE
Incorrect manifest URL in Foundry Add-ons directory

### ISSUE THREAD

**Issue by KenGitsIt** [jessev14/custom-character-sheet-sections#2]
It currently points to https://github.com/jessev14/custom-rarities-and-currencies/releases/download/1.0.0/module.json.

**Comment by jessev14** [comment]
you can still update the module in foundry. foundry will pull the latest version.

**Comment by KenGitsIt** [comment]
This problem isn't about updating the module; it's about the initial installation.  Users trying to install it through Foundry's automated installer will actually install the wrong module.  I was able to install it by manually entering the correct manifest URL, but other users may simply give up and not install it at all.

**Comment by jessev14** [comment]
wow I'm an idiot how did I mess that up. fixed, thank you very much for pointing it out
