### ISSUE TITLE
Bug: Flickering while a characters sheet is open by both the player and the GM

### ISSUE THREAD

**Issue by netenes** [jessev14/custom-character-sheet-sections#21]
It flickers and refreshes making it almost impossible to use the sheet if both gm and player has it open. 

https://github.com/jessev14/custom-character-sheet-sections/assets/60858343/1f77fa47-ba0d-4a40-bb13-bfba750b238e

**Comment by jessev14** [comment]
This only happens when the sheet is opened by a GM and a user? I'm not able to recreate the bug. Are there any errors in the console? 

https://streamable.com/bzsf9y
