### ISSUE TITLE
FATAL BUG with D&D 5e's 3.0.0. Character Sheets

### ISSUE THREAD

**Issue by StarOfChorusim** [jessev14/custom-character-sheet-sections#22]
Myself and a friend of mine who is also a DM have encountered with this module that has that was kicking back actor ID errors and was deleting things off the character sheet, in my friend's words, "It would try and make the sheet compatible by force, only to get an error, and try again. Hence why it would undo some info upon entering it in, because the sheet wasn't given time to refresh or accept the new info."
We'll need a forward port to D&D 3.0.0. at some point and making it compatible with the new sheet! 
This is one of my favorite modules so seeing it updated would be incredible. D:

**Comment by jessev14** [comment]
Can I get some screenshots of the errors?

**Comment by mflaherty97** [comment]
@StarOfChorusim do you have any updates on this? I've also been wanting to use this module.
