### ISSUE TITLE
{Bug} Not working on dnd5e 3.1.2

### ISSUE THREAD

**Issue by maxobremer** [jessev14/custom-character-sheet-sections#26]
Tried this module in dnd5e 3.1.2 and didnt work. Here is my set up in a test world:
![image](https://github.com/jessev14/custom-character-sheet-sections/assets/86924581/7d877a73-1d6c-4172-a6f5-f3186942c5fb)

**Comment by jessev14** [comment]
Update the module.

**Comment by maxobremer** [comment]
oh weird cause i installed it, like after you pushed the 2.1.0 update, so was expecting it to be the latest version. After updating it works
