### ISSUE TITLE
[Bug]Not working on Tidy 5e Sheets 4.0.2

### ISSUE THREAD

**Issue by kagangtuya-star** [jessev14/custom-character-sheet-sections#29]
Not working on Tidy 5e Sheets 4.0.2...

The environment is as follows.
Foundry v11.315
dnd5e 3.2.0
![image](https://github.com/jessev14/custom-character-sheet-sections/assets/73411104/e842465a-9029-4c0e-88bf-43a4a996a6fb)

![image](https://github.com/jessev14/custom-character-sheet-sections/assets/73411104/0ec7e907-591c-450a-8327-707b8b8ae289)

Additionally, the console has displayed the following error log.
```
foundry.js:733  Foundry VTT | Error thrown in hooked function 'preUpdateItemHook' for hook 'preUpdateItem'

TypeError: Cannot read properties of undefined (reading 'attuned')
    at Object.preUpdateItemHook [as fn] (DAEdnd5e.js:1417:110)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at #preUpdateDocumentArray (foundry.js:13674:44)
    at async ClientDatabaseBackend._updateDocuments (foundry.js:13449:22)
    at async Item5e.updateDocuments (commons.js:8001:23)
    at async Item5e.update (commons.js:8098:23)
    at async Tidy5eKgarItemSheet._onSubmit (foundry.js:6626:7)
    at async Tidy5eKgarItemSheet._onSubmit (item-sheet.mjs:888:5)
    at async Tidy5eKgarItemSheet._onSubmit (Tidy5eItemSheet.ts:239:11)
    at async Tidy5eKgarItemSheet.submit (foundry.js:6947:5)

```
![image](https://github.com/jessev14/custom-character-sheet-sections/assets/73411104/34af6038-a683-4551-9b9e-fe28e171493f)

Another potentially useful piece of information is that it works fine in other table templates.

**Comment by kgar** [comment]
Tidy 5e dev here 👋

Tidy 5e Sheets does its own custom sections now. It intentionally does not use the CCSS settings.
The inputs above the Custom Section input are Tidy's own fields for custom sections.

![image](https://github.com/jessev14/custom-character-sheet-sections/assets/4632129/018e5f22-2cd8-4500-9246-f29085db98e0)

If you'd like to import CCSS settings to Tidy's side, there's a migration for it. The migration can just copy values over, as long as you do not use the "Delete Flags" option:

![image](https://github.com/jessev14/custom-character-sheet-sections/assets/4632129/5b7a62d3-bc12-4c5f-b6cb-adf6c09a2a73)

With that said, CCSS is now meant for supported sheets other than Tidy, and Tidy is doing it's own thing with custom sections, going forward. They can coexist in the same world, but Tidy handles its own custom sectioning.

**Comment by kagangtuya-star** [comment]
It turns out that it is like this...Thanks!
