### ISSUE TITLE
Doesn't seem to work on spells

### ISSUE THREAD

**Issue by TheDraggo** [jessev14/custom-character-sheet-sections#3]
Hey! This is probably one of my dream modules finally come true so thanks <3 

While I can get it to work with items and features it doesn't seem to work with the spellbook section (which could be useful with multiclassing casters).

**Comment by jessev14** [comment]
I intentionally left out spells cause I felt like spell level was the most effective way to section them.
I can add spell handling to the module, but there's not going to be a great way to automatically track what level a spell is or how many slots you have to cast it:

![image](https://user-images.githubusercontent.com/68755874/157738626-9b67178c-d2b9-4fc5-b094-5ac4fe116d95.png)

**Comment by TheDraggo** [comment]
Yeah I thought so. Probably wouldn't be the most optimal way to track multiclassed spells. 

I can still get a lot of use out of it through maneuvers, metamagic, subclass features, backpacks, etc though so thank you :)

**Comment by jessev14** [comment]
oh, no i still did it, it's on the 1.2.0 version
