### ISSUE TITLE
Randomly not able to view other PCs with limited access

### ISSUE THREAD

**Issue by ChobitsCrazy** [jessev14/custom-character-sheet-sections#32]
With only CCSS and libWrapper enabled for certain PCs the other players who have limited access to the actor are unable to view the actor and get a access denied message:
![image](https://github.com/jessev14/custom-character-sheet-sections/assets/21301107/e131be6e-2123-4416-beda-833ace4d671c)

It doesn't happen for every PC and I haven't quite tracked down the reason for the error yet but here is a copy of one example actor that is affected:
[fvtt-Actor-grit-UJbdXMSeJMhkjCLF.json](https://github.com/user-attachments/files/15782289/fvtt-Actor-grit-UJbdXMSeJMhkjCLF.json)

Foundry: v11.315
DND: 3.1.2
CCSS: 2.1.0

**Comment by jessev14** [comment]
Fixed in v2.2.0.
