### ISSUE TITLE
[feature] Display charges/uses while in a custom section

### ISSUE THREAD

**Issue by Orionox** [jessev14/custom-character-sheet-sections#5]
So currently when you move an item to a custom section you lose the ability to see charges. It would be nice if that functionality could be retained when something gets put in a custom section.

**Comment by jessev14** [comment]
Can you share a screen shot of what you're seeing? It looks like you can still see charges ("Backpack" is a Custom Section).
![image](https://user-images.githubusercontent.com/68755874/160300667-1628101c-2077-4eb3-b51b-bcb189ef5dd7.png)

**Comment by jessev14** [comment]
If you were referring to Features, I see the issue. I'll release an update later today to address it.

**Comment by Orionox** [comment]
Yes, I was referring to features. Sorry about the confusion

**Comment by jessev14** [comment]
Added in v1.3.0. You can update the module now to get it.
