### ISSUE TITLE
Suggestion: Add in an "Add+" To catorgry

### ISSUE THREAD

**Issue by pontusedberg** [jessev14/custom-character-sheet-sections#6]
can you add in an "Add+" to the categories? So its easier to add in new items? 

![b](https://user-images.githubusercontent.com/1547673/160908252-2997476e-ee44-4b2e-a7ba-afef1ff10f85.png)
![a](https://user-images.githubusercontent.com/1547673/160908233-ab2c2a4a-8781-43b5-b52d-508ce963779d.png)

**Comment by jessev14** [comment]
I originally planned to have this, but it doesn't really make sense.

When you click that item, Foundry creates a new item of the type for that section (e.g. if you click the Add button under the Loot section, it makes a new Loot item). Custom Sections, however, can have items of any types (e.g. an armor and a weapon can both be under a Custom Section).

So if you click the Add button under a Custom Section, how would the game know what type of item you want to make?

**Comment by pontusedberg** [comment]
a magic item
