### ISSUE TITLE
v10 version is throwing (harmless) console errors and warnings

### ISSUE THREAD

**Issue by krbz999** [jessev14/custom-character-sheet-sections#9]
This warning is thrown when opening a class/subclass/background item sheet.

![image](https://user-images.githubusercontent.com/50169243/189760172-c98ebe54-b349-4f11-9ecb-10c33278d738.png)

There is also a deprecation warning on startup about 'author' in the module.json.

**Comment by jessev14** [comment]
Thanks for the heads up. Fixed in version 1.4.1.
